### ISSUE TITLE
Upgrade please

### ISSUE THREAD

**Issue by MoonDragon-MD** [yauhen-l/remember-last-position-totem-plugin#3]
Hi, I tried to use your plugin with totem 3.34 but since there is no auto-start option the plugin doesn't work. Have you ever thought to update it?
Thanks

**Comment by yauhen-l** [comment]
Hi @MoonDragon-MD ,
Plugin was never intended to restore the last played file and auto-start. It only remembers the last position in a played video file. You can close Totem or play other videos, but if you come back to the original video file a playback will start for the last position minus few seconds. This still works fine on my `totem-3.34.1-4.fc32.x86_64`.

**Comment by MoonDragon-MD** [comment]
Thank you for specifying the operation! It is a good add-on, nice work, thank you
